project_id = "chpplckgndznakuvcqbx"

[functions.track-event]
verify_jwt = false

[functions.storefront-cache]
verify_jwt = false

[functions.check-slug]
verify_jwt = false

[functions.create-shop]
verify_jwt = false

[functions.track-link-click]
verify_jwt = false

[functions.track-campaign-event]
verify_jwt = false

[functions.notify-order]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
