
INSERT INTO public.email_templates (slug, name, subject, body, is_active) VALUES

('email_verification', 'Vérification email', 'Vérifiez votre adresse email', '<h2 style="margin:0 0 15px;font-size:20px;">Bienvenue sur Ventou ! 🎉</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Merci de vous être inscrit. Veuillez vérifier votre adresse email en cliquant sur le bouton ci-dessous :</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{verification_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Vérifier mon email</a></td></tr></table><p style="font-size:13px;color:#6b7280;">Si vous n''avez pas créé de compte, ignorez cet email.</p>', true),

('password_reset', 'Réinitialisation mot de passe', 'Réinitialisez votre mot de passe', '<h2 style="margin:0 0 15px;font-size:20px;">Réinitialisation du mot de passe 🔐</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Vous avez demandé la réinitialisation de votre mot de passe. Cliquez sur le bouton ci-dessous :</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{reset_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Réinitialiser</a></td></tr></table><p style="font-size:13px;color:#6b7280;">Ce lien expire dans 1 heure. Si vous n''avez pas fait cette demande, ignorez cet email.</p>', true),

('two_factor_code', 'Code 2FA', 'Votre code de vérification', '<h2 style="margin:0 0 15px;font-size:20px;">Code de vérification 🔑</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Voici votre code de vérification à usage unique :</p><table cellpadding="0" cellspacing="0" style="margin:25px auto;text-align:center;"><tr><td style="background:#f3f4f6;border-radius:10px;padding:20px 40px;font-size:32px;font-weight:700;letter-spacing:8px;color:#111827;">{{code}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Ce code expire dans 10 minutes.</p>', true),

('account_approved', 'Compte approuvé', 'Votre compte a été approuvé ✅', '<h2 style="margin:0 0 15px;font-size:20px;">Compte approuvé ! ✅</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre compte a été vérifié et approuvé par notre équipe. Vous pouvez maintenant accéder à toutes les fonctionnalités de la plateforme.</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Accéder au dashboard</a></td></tr></table>', true),

('account_suspended', 'Compte suspendu', 'Votre compte a été suspendu', '<h2 style="margin:0 0 15px;font-size:20px;">Compte suspendu ⚠️</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre compte a été suspendu pour la raison suivante :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;color:#991b1b;font-size:14px;">{{reason}}</td></tr></table><p>Si vous pensez qu''il s''agit d''une erreur, contactez notre support.</p>', true),

('welcome_vendor', 'Bienvenue vendeur', 'Bienvenue sur Ventou ! 🚀', '<h2 style="margin:0 0 15px;font-size:20px;">Bienvenue sur Ventou ! 🚀</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Merci d''avoir rejoint Ventou. Voici vos prochaines étapes :</p><table cellpadding="0" cellspacing="0" style="margin:20px 0;width:100%;"><tr><td style="padding:8px 0;font-size:14px;">✅ Créez votre première boutique</td></tr><tr><td style="padding:8px 0;font-size:14px;">📦 Ajoutez vos produits</td></tr><tr><td style="padding:8px 0;font-size:14px;">🔗 Partagez votre lien</td></tr><tr><td style="padding:8px 0;font-size:14px;">💰 Recevez vos premières commandes</td></tr></table><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Commencer maintenant</a></td></tr></table>', true),

('store_created', 'Boutique créée', 'Votre boutique {{store_name}} est en ligne ! 🎉', '<h2 style="margin:0 0 15px;font-size:20px;">Boutique créée ! 🎉</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> est maintenant en ligne à l''adresse :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#f0fdf4;border-radius:8px;padding:15px;text-align:center;"><a href="{{store_url}}" style="color:#111827;font-weight:700;font-size:16px;text-decoration:none;">{{store_url}}</a></td></tr></table><p>Commencez à ajouter des produits pour recevoir vos premières commandes !</p>', true),

('store_approved', 'Boutique approuvée', 'Votre boutique {{store_name}} a été approuvée ✅', '<h2 style="margin:0 0 15px;font-size:20px;">Boutique approuvée ! ✅</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> a été vérifiée et approuvée.</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{store_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Voir ma boutique</a></td></tr></table>', true),

('store_rejected', 'Boutique rejetée', 'Votre boutique {{store_name}} nécessite des modifications', '<h2 style="margin:0 0 15px;font-size:20px;">Boutique non approuvée ❌</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> n''a pas pu être approuvée :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;color:#991b1b;font-size:14px;">{{reason}}</td></tr></table><p>Veuillez effectuer les modifications nécessaires.</p>', true),

('store_suspended', 'Boutique suspendue', 'Votre boutique {{store_name}} a été suspendue', '<h2 style="margin:0 0 15px;font-size:20px;">Boutique suspendue ⚠️</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> a été suspendue :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;color:#991b1b;font-size:14px;">{{reason}}</td></tr></table><p>Les clients ne peuvent plus passer de commandes.</p>', true),

('store_reactivated', 'Boutique réactivée', 'Votre boutique {{store_name}} est de retour ! 🎉', '<h2 style="margin:0 0 15px;font-size:20px;">Boutique réactivée ! 🎉</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> est à nouveau accessible.</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{store_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Voir ma boutique</a></td></tr></table>', true),

('new_order_vendor', 'Nouvelle commande vendeur', '🛒 Nouvelle commande #{{order_id}} — {{total}}', '<h2 style="margin:0 0 15px;font-size:20px;">Nouvelle commande ! 🛒</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Vous avez reçu une nouvelle commande sur <strong>{{store_name}}</strong> :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;"><tr style="background:#f9fafb;"><td style="padding:10px 15px;font-weight:600;font-size:13px;color:#6b7280;">Commande</td><td style="padding:10px 15px;font-weight:600;font-size:13px;color:#6b7280;">Client</td><td style="padding:10px 15px;font-weight:600;font-size:13px;color:#6b7280;">Total</td></tr><tr><td style="padding:10px 15px;font-size:14px;">#{{order_id}}</td><td style="padding:10px 15px;font-size:14px;">{{customer_name}}<br/><span style="color:#6b7280;font-size:12px;">{{customer_phone}}</span></td><td style="padding:10px 15px;font-size:14px;font-weight:700;">{{total}}</td></tr></table><table cellpadding="0" cellspacing="0" style="margin:10px 0;width:100%;"><tr><td style="padding:5px 0;font-size:13px;">📍 {{city}}{{quartier}}</td></tr><tr><td style="padding:5px 0;font-size:13px;">💳 {{payment_method}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Articles : {{items_list}}</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Voir la commande</a></td></tr></table>', true),

('order_confirmation_customer', 'Confirmation commande client', 'Commande confirmée #{{order_id}} ✅', '<h2 style="margin:0 0 15px;font-size:20px;">Commande confirmée ! ✅</h2><p>Bonjour <strong>{{customer_name}}</strong>,</p><p>Votre commande <strong>#{{order_id}}</strong> sur <strong>{{store_name}}</strong> a bien été enregistrée.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;"><tr style="background:#f9fafb;"><td style="padding:10px 15px;font-size:13px;font-weight:600;color:#6b7280;">Articles</td><td style="padding:10px 15px;font-size:13px;font-weight:600;color:#6b7280;text-align:right;">Total</td></tr><tr><td style="padding:10px 15px;font-size:14px;">{{items_list}}</td><td style="padding:10px 15px;font-size:14px;font-weight:700;text-align:right;">{{total}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Paiement : {{payment_method}} · Livraison à {{city}}</p><p>Le vendeur vous contactera bientôt. Merci ! 🙏</p>', true),

('order_cancelled', 'Commande annulée', 'Commande #{{order_id}} annulée', '<h2 style="margin:0 0 15px;font-size:20px;">Commande annulée ❌</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>La commande <strong>#{{order_id}}</strong> sur <strong>{{store_name}}</strong> a été annulée.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;color:#991b1b;font-size:14px;">Raison : {{reason}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Montant : {{total}}</p>', true),

('order_refunded', 'Commande remboursée', 'Remboursement commande #{{order_id}}', '<h2 style="margin:0 0 15px;font-size:20px;">Commande remboursée 💸</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>La commande <strong>#{{order_id}}</strong> a été remboursée.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#f0fdf4;border-left:4px solid #22c55e;padding:15px;border-radius:0 8px 8px 0;font-size:14px;"><strong>Montant remboursé :</strong> {{amount}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Remboursement sous 5 à 10 jours ouvrés.</p>', true),

('order_shipped', 'Commande expédiée', 'Votre commande #{{order_id}} a été expédiée 🚚', '<h2 style="margin:0 0 15px;font-size:20px;">Commande expédiée ! 🚚</h2><p>Bonjour <strong>{{customer_name}}</strong>,</p><p>Votre commande <strong>#{{order_id}}</strong> sur <strong>{{store_name}}</strong> a été expédiée.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#eff6ff;border-left:4px solid #3b82f6;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">📦 Votre colis est en route !</td></tr></table>', true),

('order_delivered', 'Commande livrée', 'Votre commande #{{order_id}} a été livrée ✅', '<h2 style="margin:0 0 15px;font-size:20px;">Commande livrée ! ✅</h2><p>Bonjour <strong>{{customer_name}}</strong>,</p><p>Votre commande <strong>#{{order_id}}</strong> sur <strong>{{store_name}}</strong> a bien été livrée.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#f0fdf4;border-left:4px solid #22c55e;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">🎉 Profitez de vos achats !</td></tr></table><p>N''hésitez pas à laisser un avis.</p>', true),

('subscription_activated', 'Abonnement activé', 'Votre abonnement {{plan_name}} est actif ! 🎉', '<h2 style="margin:0 0 15px;font-size:20px;">Abonnement activé ! 🎉</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre abonnement <strong>{{plan_name}}</strong> est actif.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;"><tr><td style="padding:10px 15px;font-size:13px;color:#6b7280;">Plan</td><td style="padding:10px 15px;font-weight:700;">{{plan_name}}</td></tr><tr style="background:#f9fafb;"><td style="padding:10px 15px;font-size:13px;color:#6b7280;">Période</td><td style="padding:10px 15px;">{{period_start}} — {{period_end}}</td></tr></table>', true),

('subscription_expiring_7_days', 'Abonnement expire dans 7 jours', 'Votre abonnement expire dans 7 jours ⏰', '<h2 style="margin:0 0 15px;font-size:20px;">Expiration dans 7 jours ⏰</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre abonnement <strong>{{plan_name}}</strong> expire le <strong>{{expiry_date}}</strong>.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fffbeb;border-left:4px solid #f59e0b;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">Renouvelez pour ne pas perdre vos avantages.</td></tr></table><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Renouveler</a></td></tr></table>', true),

('subscription_expiring_1_day', 'Abonnement expire demain', '⚠️ Votre abonnement expire demain !', '<h2 style="margin:0 0 15px;font-size:20px;">Expiration demain ! ⚠️</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre abonnement <strong>{{plan_name}}</strong> expire <strong>demain</strong>.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;font-size:14px;font-weight:600;">Renouvelez immédiatement !</td></tr></table><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Renouveler maintenant</a></td></tr></table>', true),

('subscription_expired', 'Abonnement expiré', 'Votre abonnement a expiré', '<h2 style="margin:0 0 15px;font-size:20px;">Abonnement expiré 😢</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre abonnement <strong>{{plan_name}}</strong> a expiré. Vos boutiques sont limitées au plan gratuit.</p><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Réactiver</a></td></tr></table>', true),

('plan_upgraded', 'Plan amélioré', 'Vous êtes passé au plan {{plan_name}} ! 🚀', '<h2 style="margin:0 0 15px;font-size:20px;">Plan amélioré ! 🚀</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Vous êtes sur le plan <strong>{{plan_name}}</strong>.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#f0fdf4;border-left:4px solid #22c55e;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">{{plan_features}}</td></tr></table>', true),

('plan_downgraded', 'Plan réduit', 'Votre plan a été modifié', '<h2 style="margin:0 0 15px;font-size:20px;">Plan modifié ℹ️</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre abonnement est passé au plan <strong>{{plan_name}}</strong>.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fffbeb;border-left:4px solid #f59e0b;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">Limites : {{plan_limits}}</td></tr></table><p>Passez à un plan supérieur à tout moment.</p>', true),

('vendor_report_warning', 'Avertissement signalement', 'Avertissement : signalement sur votre boutique', '<h2 style="margin:0 0 15px;font-size:20px;">Avertissement ⚠️</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre boutique <strong>{{store_name}}</strong> a reçu un signalement :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;color:#991b1b;font-size:14px;">{{reason}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Signalements : {{report_count}}</p>', true),

('manual_admin_action', 'Action admin', 'Action administrative sur votre compte', '<h2 style="margin:0 0 15px;font-size:20px;">Notification administrative 📋</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Action effectuée :</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#eff6ff;border-left:4px solid #3b82f6;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">{{action_description}}</td></tr></table>', true),

('payment_failed', 'Paiement échoué', 'Échec de paiement ❌', '<h2 style="margin:0 0 15px;font-size:20px;">Paiement échoué ❌</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Le paiement pour <strong>{{plan_name}}</strong> a échoué.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;"><tr><td style="background:#fef2f2;border-left:4px solid #ef4444;padding:15px;border-radius:0 8px 8px 0;font-size:14px;">Montant : {{amount}} · Erreur : {{error_message}}</td></tr></table><table cellpadding="0" cellspacing="0" style="margin:25px 0;"><tr><td style="background:#111827;border-radius:8px;padding:12px 30px;"><a href="{{dashboard_url}}" style="color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;">Mettre à jour</a></td></tr></table>', true),

('payment_success', 'Paiement réussi', 'Paiement confirmé ✅', '<h2 style="margin:0 0 15px;font-size:20px;">Paiement réussi ! ✅</h2><p>Bonjour <strong>{{name}}</strong>,</p><p>Votre paiement a été traité.</p><table cellpadding="0" cellspacing="0" style="margin:15px 0;width:100%;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;"><tr><td style="padding:10px 15px;font-size:13px;color:#6b7280;">Plan</td><td style="padding:10px 15px;font-weight:700;">{{plan_name}}</td></tr><tr style="background:#f9fafb;"><td style="padding:10px 15px;font-size:13px;color:#6b7280;">Montant</td><td style="padding:10px 15px;">{{amount}}</td></tr><tr><td style="padding:10px 15px;font-size:13px;color:#6b7280;">Date</td><td style="padding:10px 15px;">{{payment_date}}</td></tr></table><p style="font-size:13px;color:#6b7280;">Merci ! 🙏</p>', true)

ON CONFLICT (slug) DO NOTHING;
